// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF8XgnD6F2quR8ImKJqXQa352gvhaGG2I',
    appId: '1:1073837037972:web:c31a5665c9f4d9d07dd781',
    messagingSenderId: '1073837037972',
    projectId: 'just-order-cbc6a',
    authDomain: 'just-order-cbc6a.firebaseapp.com',
    storageBucket: 'just-order-cbc6a.appspot.com',
    measurementId: 'G-D586QHWLCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVk6rBqSvlf3gYnqCqLLGq3_pBTh37SYc',
    appId: '1:1073837037972:android:32cf45f6ba9342387dd781',
    messagingSenderId: '1073837037972',
    projectId: 'just-order-cbc6a',
    storageBucket: 'just-order-cbc6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwmt6gUbOXhiShlbgTBwp5mWA99_bX5MQ',
    appId: '1:1073837037972:ios:7e9634231e20b6b77dd781',
    messagingSenderId: '1073837037972',
    projectId: 'just-order-cbc6a',
    storageBucket: 'just-order-cbc6a.appspot.com',
    iosBundleId: 'com.JustOrder.justOrder',
  );
}
